const { type } = require('express/lib/response');

const pokemonArr = [
  {
    pokemon_name: 'bulbasaur',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/VN6df4o.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'ivysaur',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/gktbDGb.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'venusaur',
    type: 'Grass, Poison',
    iamgeUrl: 'https://i.imgur.com/0liEa8F.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'charmander',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/HOjIuKA.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'charmeleon',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/kKSB3U3.jpeg',
    price: 9,
    quantity: 10,
  },
  {
    pokemon_name: 'charizard',
    type: 'Fire, Flying',
    imageUrl: 'https://i.imgur.com/4mI8dBA.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'squirtle',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/lHHHiNh.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'wartortle',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/Yd3LVZI.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'blastoise',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/EXJDRhw.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'caterpie',
    type: 'Bug',
    imageUrl: 'https://i.imgur.com/ZycId9a.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'metapod',
    type: 'Bug',
    imageUrl: 'https://i.imgur.com/8drBAVu.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'butterfree',
    type: 'Bug, Flying',
    imageUrl: 'https://i.imgur.com/t7oaYHl.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'weedle',
    type: 'Bug, Poison',
    imageUrl: 'https://i.imgur.com/Ff2IPEr.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'kakuna',
    type: 'Bug, Poison',
    imageUrl: 'https://i.imgur.com/eF5uT9e.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'beedrill',
    type: 'Bug, Poison',
    imageUrl: 'https://i.imgur.com/AwXlJOM.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'pidgey',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/DyW28fI.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'pidgeotto',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/KEWWBDz.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'pidgeot',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/Isp7ZR8.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'rattata',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/LIe3ZLt.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'raticate',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/Bhf34OF.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'spearow',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/pCatj7Z.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'fearow',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/C7UwKqL.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'ekans',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/nHbxnyS.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'arbok',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/aH8PTbs.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'pikachu',
    type: 'Electric',
    imageUrl: 'https://i.imgur.com/4SrGCdX.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'raichu',
    type: 'Electric',
    imageUrl: 'https://i.imgur.com/VOc1Gxp.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'sandshrew',
    type: 'Ground',
    imageUrl: 'https://i.imgur.com/VhBLL6V.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'sandslash',
    type: 'Ground',
    imageUrl: 'https://i.imgur.com/fFazao0.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'nidoran-f',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/xXlBKf5.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'nidorina',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/gjHiDlj.jpeg/',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'nidoqueen',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/emaLahw.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'nidoran-m',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/MyiD3Cm.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'nidorino',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/Nfb7TGJ.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'nidoking',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/z17kift.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'clefairy',
    type: 'Bug',
    imageUrl: 'https://i.imgur.com/CQACXLN.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'clefable',
    type: 'Fairy',
    imageUrl: 'https://i.imgur.com/PKTdqX7.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'vulpix',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/anumWPm.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'ninetales',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/BsiJHcr.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'jigglypuff',
    type: 'Normal, Fairy',
    imageUrl: 'https://i.imgur.com/ROrTahE.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'wigglytuff',
    type: 'Normal, Fairy',
    imageUrl: 'https://i.imgur.com/jGUNMln.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'zubat',
    type: 'Poison, Flying',
    imageUrl: 'https://i.imgur.com/XcE9Yt7.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'golbat',
    type: 'Poison, Flying',
    imageUrl: 'https://i.imgur.com/mQah8G0.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'oddish',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/dehfWs9.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'gloom',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/xCMibYC.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'vileplume',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/XQKhnhN.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'paras',
    type: 'Bug, Grass',
    imageUrl: 'https://i.imgur.com/KurxNRa.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'parasect',
    type: 'Bug, Grass',
    imageUrl: 'https://i.imgur.com/7PJe4sJ.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'venonat',
    type: 'Bug, Poison',
    imageUrl: 'https://i.imgur.com/9qUyaaX.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'venomoth',
    type: 'Bug, Poison',
    imageUrl: 'https://i.imgur.com/S8AdnGV.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'diglett',
    type: 'Ground',
    imageUrl: 'https://i.imgur.com/H56otDx.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'dugtrio',
    type: 'Ground',
    imageUrl: 'https://i.imgur.com/EibRcjQ.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'meowth',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/TlPRD2d.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'persian',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/0DDug1o.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'psyduck',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/kXfAI8l.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'golduck',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/jLQqU7I.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'mankey',
    type: 'Fighting',
    imageUrl: 'https://i.imgur.com/xhGDYGK.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'primeape',
    type: 'Fighting',
    imageUrl: 'https://i.imgur.com/hkonqgU.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'growlithe',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/nYfelHI.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'arcanine',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/G5LI3G8.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'poliwag',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/PJ1ENgC.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'poliwhirl',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/nEFTNv5.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'poliwrath',
    type: 'Water, Fighting',
    imageUrl: 'https://i.imgur.com/dbg0shr.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'abra',
    type: 'Psychic',
    imageUrl: 'https://i.imgur.com/CDzuaWN.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'kadabra',
    type: 'Psychic',
    imageUrl: 'https://i.imgur.com/pIgbAWm.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'alakazam',
    type: 'Psychic',
    imageUrl: 'https://i.imgur.com/xlSt3tS.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'machop',
    type: 'Fighting',
    imageUrl: 'https://i.imgur.com/PNTbgVd.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'machoke',
    type: 'Fighting',
    imageUrl: 'https://i.imgur.com/jfcUfwI.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'machamp',
    type: 'Fighting',
    imageUrl: 'https://i.imgur.com/rnCHg0O.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'bellsprout',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/Tcgxz3m.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'weepinbell',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/hCXAyiw.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'victreebel',
    type: 'Grass, Poison',
    imageUrl: 'https://i.imgur.com/EgGId1U.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'tentacool',
    type: 'Water, Poison',
    imageUrl: 'https://i.imgur.com/9jKJCwM.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'tentacruel',
    type: 'Water, Poison',
    imageUrl: 'https://i.imgur.com/X9PslWV.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'geodude',
    type: 'Rock, Ground',
    imageUrl: 'https://i.imgur.com/LVAwAPc.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'graveler',
    type: 'Rock, Ground',
    imageUrl: 'https://i.imgur.com/iW5o9Jv.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'golem',
    type: 'Rock, Ground',
    imageUrl: 'https://i.imgur.com/R1T66t3.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'ponyta',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/rypSExt.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'rapidash',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/rUiPMNV.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'slowpoke',
    type: 'Water, Psychic',
    imageUrl: 'https://i.imgur.com/Uo2gswf.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'slowbro',
    type: 'Water, Psychic',
    imageUrl: 'https://i.imgur.com/CD7gGVx.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'magnemite',
    type: 'Electric, Steel',
    imageUrl: 'https://i.imgur.com/SvEC8Hh.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'magneton',
    type: 'Electric, Steel',
    imageUrl: 'https://i.imgur.com/nLjpUHM.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'farfetchd',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/fSepXZj.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'doduo',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/rEXwuiw.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'dodrio',
    type: 'Normal, Flying',
    imageUrl: 'https://i.imgur.com/jVq4xar.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'seel',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/YSMGYyu.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'dewgong',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/VAJ6GtL.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'grimer',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/ZYrjLDV.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'muk',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/bAqJQf3.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'shellder',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/jrUNlPN.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'cloyster',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/8RkFQny.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'gastly',
    type: 'Ghost, Poison',
    imageUrl: 'https://i.imgur.com/S4vIZuQ.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'haunter',
    type: 'Ghost, Poison',
    imageUrl: 'https://i.imgur.com/VXDpVXj.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'gengar',
    type: 'Ghost, Poison',
    imageUrl: 'https://i.imgur.com/PtKdgyc.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'onix',
    type: 'Rock, Ground',
    imageUrl: 'https://i.imgur.com/T0G7czE.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'drowzee',
    type: 'Psychic',
    imageUrl: 'https://i.imgur.com/eIfMJwW.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'hypno',
    type: 'Psychic',
    imageUrl: 'https://i.imgur.com/VJGv6B9.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'krabby',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/sqYPAXX.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'kingler',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/Nlrs71U.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'voltorb',
    type: 'Electric',
    imageUrl: 'https://i.imgur.com/lfAYoh6.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'electrode',
    type: 'Electric',
    imageUrl: 'https://i.imgur.com/CpF1nYy.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'exeggcute',
    type: 'Grass, Psychic',
    imageUrl: 'https://i.imgur.com/xyLW37j.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'exeggutor',
    type: 'Grass, Psychic',
    imageUrl: 'https://i.imgur.com/0ZQ1SEm.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'cubone',
    type: 'Ground',
    imageUrl: 'https://i.imgur.com/EnYNIGM.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'marowak',
    type: 'Ground',
    imageUrl: 'https://i.imgur.com/To5as6p.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'hitmonlee',
    type: 'Fighting',
    imageUrl: 'https://i.imgur.com/HzHPT7u.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'hitmonchan',
    type: 'Fighting',
    imageUrl: 'https://i.imgur.com/ZAXu2Wc.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'lickitung',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/IxLzpv8.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'koffing',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/B2NCk1x.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'weezing',
    type: 'Poison',
    imageUrl: 'https://i.imgur.com/KGavDDz.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'rhyhorn',
    type: 'Ground, Rock',
    imageUrl: 'https://i.imgur.com/FupyBEh.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'rhydon',
    type: 'Ground, Rock',
    imageUrl: 'https://i.imgur.com/mG2x6mn.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'chansey',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/j6lYURt.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'tangela',
    type: 'Grass',
    imageUrl: 'https://i.imgur.com/d0pH3jJ.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'kangaskhan',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/WCBM60l.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'horsea',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/hPJDz9s.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'seadra',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/0sBpEWn.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'goldeen',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/sjD6jjp.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'seaking',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/jSwRMPu.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'staryu',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/MJ4Tq3S.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'starmie',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/IwyMpFo.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'mr-mime',
    type: 'Psychic, Fairy',
    imageUrl: 'https://i.imgur.com/AolSJTf.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'scyther',
    type: 'Bug, Flying',
    imageUrl: 'https://i.imgur.com/ETgwGYK.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'jynx',
    type: 'Ice, Psychic',
    imageUrl: 'https://i.imgur.com/2DK6aEu.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'electabuzz',
    type: 'Electric',
    imageUrl: 'https://i.imgur.com/VTlw60a.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'magmar',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/5Fu8RcL.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'pinsir',
    type: 'Bug',
    imageUrl: 'https://i.imgur.com/Orx7o0E.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'tauros',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/3cC6rPn.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'magikarp',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/nbxoMDn.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'gyarados',
    type: 'Water, Flying',
    imageUrl: 'https://i.imgur.com/YRrbP9f.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'lapras',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/w87ZZ80.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'ditto',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/juGlzg0.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'eevee',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/7uoeLgG.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'vaporeon',
    type: 'Water',
    imageUrl: 'https://i.imgur.com/FprzdCt.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'jolteon',
    type: 'Electric',
    imageUrl: 'https://i.imgur.com/mNNnCkS.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'flareon',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/PTVe3TB.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'porygon',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/KyQyCdv.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'omanyte',
    type: 'Rock, Water',
    imageUrl: 'https://i.imgur.com/4RFzPj9.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'omastar',
    type: 'Rock, Water',
    imageUrl: 'https://i.imgur.com/yge9fQI.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'kabuto',
    type: 'Rock, Water',
    imageUrl: 'https://i.imgur.com/lUDnrk6.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'kabutops',
    type: 'Rock, Water',
    imageUrl: 'https://i.imgur.com/TcwiOvv.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'aerodactyl',
    type: 'Rock, Flying',
    imageUrl: 'https://i.imgur.com/oW0ZxfW.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'snorlax',
    type: 'Normal',
    imageUrl: 'https://i.imgur.com/Hlwaziz.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'articuno',
    type: 'Ice, Flying',
    imageUrl: 'https://i.imgur.com/EREOJBj.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'zapdos',
    type: 'Electric',
    imageUrl: 'https://i.imgur.com/BwXCCKJ.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'moltres',
    type: 'Fire',
    imageUrl: 'https://i.imgur.com/9h9f44p.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'dratini',
    type: 'Dragon',
    imageUrl: 'https://i.imgur.com/KRlqWJE.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'dragonair',
    type: 'Dragon',
    imageUrl: 'https://i.imgur.com/5VoV8es.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'dragonite',
    type: 'Dragon',
    imageUrl: 'https://i.imgur.com/5iLnel4.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
  {
    pokemon_name: 'mewtwo',
    type: 'Psychic',
    imageUrl: 'https://i.imgur.com/iFop2sr.jpeg',
    price: 9,
    description: 'Description to be added here',
    quantity: 10,
  },
];
module.exports = pokemonArr;
